# Generated by Django 4.2.7 on 2026-03-15 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalsFaculty",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.globalsextrainfo",
                    ),
                ),
            ],
            options={
                "db_table": "globals_faculty",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.globalsextrainfo",
                    ),
                ),
            ],
            options={
                "db_table": "globals_staff",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"managed": False},
        ),
        migrations.AlterModelTable(
            name="discipline",
            table="programme_curriculum_discipline",
        ),
    ]
